import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
  startup_mode = "Windowed"

[shell]
  program = "/bin/bash"
  args= ["--login", "-c", 'echo "Bonjour, $USER!" && exec /bin/bash']

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"
